# Generated by Django 4.2.1 on 2023-06-07 07:11

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='artist/images/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='customer/images/'),
        ),
    ]
