# Generated by Django 4.2.1 on 2023-06-14 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_artist_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other')], default='man'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='birth_date',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('other', 'Other')], default='man'),
            preserve_default=False,
        ),
    ]
