# Generated by Django 4.2.1 on 2023-06-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_artist_user_alter_customer_user'),
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='liked_customers',
            field=models.ManyToManyField(blank=True, related_name='liked_songs', to='user.customer'),
        ),
    ]
