# Generated by Django 4.2.1 on 2023-06-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_artist_user_alter_customer_user'),
        ('song', '0002_alter_song_liked_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='songs', to='song.playlist'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='liked_customers',
            field=models.ManyToManyField(blank=True, related_name='liked_playlists', to='user.customer'),
        ),
    ]
