# Generated by Django 4.2.1 on 2023-07-09 17:27

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_artist_user_alter_customer_user'),
        ('song', '0003_song_playlists_alter_playlist_liked_customers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlists',
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='song.song'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='playlist/images/'),
        ),
        migrations.CreateModel(
            name='ListenHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('artist', 'Artist'), ('playlist', 'Playlist')], max_length=100)),
                ('pinned', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.artist')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listen_histories', to='user.customer')),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='song.playlist')),
            ],
        ),
    ]
